manifest = "c128c0ce7054a840dcba02c610879423ccfab5d484900b14849c0393d77dc72d"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.57.0" ]
revision = "591911f924620a8610681695413d872bbc0d154d"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.57.0" ]
revision = "ee7d5652f970bde066501c7cee1d0d2ad43c2348"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.57.0" ]
revision = "d1f6b1f72f344763d683e3046948f49e11b3ff28"
