targets = [ "//:align" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
version = "1.67.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.67.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "1.67.0"
