manifest = "bb9ff1396bf07090b8fb4a528520d53882769c444ce0b3538cd2838fb5e9bf4e"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.56.0" ]
revision = "1c259a2be4292e3789436e508ea5bfe9a0750c78"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.56.0" ]
revision = "edb8562f816250216903f89ec4d9ac0961a922a1"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.56.0" ]
revision = "697d9dbf2a76b06f3052d968ab1e7f620b82d52e"
