targets = [ "//:align" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "branch=master"
