manifest = "54a260a87830aba3ea659f4e371d1c443b53fa528e9498e057ce3150ff54a079"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.65.0" ]
revision = "47c5f9c7a624feaf6d2a5408aa0b65cb164bbafb"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.65.0" ]
revision = "7268ab966b715d5702f1a2b98990626f1c193e6f"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.65.0" ]
revision = "5f5d4e0ab9c5c50fa216642014365df351ed7694"
